

module.exports = {
    PAYTM_MERCHANT_ID: 'YOUR_PAYTM_MERCHANT_ID',
    PAYTM_WEBSITE: 'YOUR_PAYTM_WEBSITE',
    PAYTM_CHANNEL_ID: 'YOUR_PAYTM_CHANNEL_ID',
    PAYTM_INDUSTRY_TYPE_ID: 'YOUR_PAYTM_INDUSTRY_TYPE_ID',
    PAYTM_MERCHANT_KEY: 'YOUR_PAYTM_MERCHANT_KEY',
    PAYTM_CALLBACK_URL: 'YOUR_PAYTM_CALLBACK_URL',
    PAYTM_PAYMENT_URL: 'YOUR_PAYTM_PAYMENT_URL'
  };
  