import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { UserProvider } from "../components/context";
import Registration from "../components/Registrationpage";
import { ToastContainer } from "react-toastify";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
       
        
        <UserProvider > 
        <Header/>
        <ToastContainer/>
          {children}

          <Footer/>
        </UserProvider>
        
        
      </body>
    </html>
  );
}
